import type { View } from "../../lib/router.ts";

export interface Feature {
  id: string;
  icon: string;
  /** A board status colour token, so a feature wears the colour of the state it is about. */
  color: string;
  title: string;
  /** What it does, in one line. */
  pitch: string;
  /** Why that is better than doing it by hand in a terminal. */
  why: string;
  /** Where to find it. */
  where: string;
  go?: View;
  /** One of the six shown in the welcome pop-up. */
  headline?: boolean;
}

export interface FeatureGroup {
  title: string;
  blurb: string;
  features: Feature[];
}

export const GROUPS: FeatureGroup[] = [
  {
    title: "It runs the work",
    blurb: "You write the card. Claude does the rest, in stages you can watch.",
    features: [
      {
        id: "pipeline",
        icon: "⇶",
        color: "var(--color-amber)",
        title: "Plan → code → review, per task",
        pitch: "Every card runs as a pipeline of Claude sessions, each stage with its own model and effort — how long it may think — picked from what your Claude login actually has. By default: plan on Opus at high effort, code on Opus at medium, review on Sonnet.",
        why: "The strongest model thinks where it matters and a cheap one tidies up. One Claude session doing all three pays top price for every step. A misspelt model shows in red in Settings, not as a failed run. When Claude ships a newer model, the board gets it and moves your picks to it by itself.",
        where: "Any task's pipeline editor",
        go: "board",
        headline: true,
      },
      {
        id: "parallel",
        icon: "⫴",
        color: "var(--color-cyan)",
        title: "Many tasks at once, or one after another",
        pitch: "Independent tasks run side by side; two that touch the same files get a dependency automatically. Chain any tasks with Starts after: queue them all, and each waits in Queued until the ones before it are done, then starts by itself with their results.",
        why: "“Find the latest order, then email its supplier” is two tasks in order — set up once, from the New task form, an open task, the graph or the chat. Switch the board to graph to see the waves and drag new links.",
        where: "New task → Starts after · a task's Spec tab · Board → graph · ✦ Chat",
        go: "board",
      },
      {
        id: "steps",
        icon: "☑",
        color: "var(--color-amber)",
        title: "See where every card is",
        pitch: "A working card shows Claude's own to-do list for the stage as one line — “3/7 · Writing the login form” — with a thin bar. Hover for the whole list.",
        why: "Ten cards at once need one progress signal that reads the same on all of them. It is read off the list Claude keeps for itself as it works, so it costs nothing.",
        where: "Any working card · the task's Claude's steps panel",
        go: "board",
      },
      {
        id: "chat",
        icon: "✦",
        color: "var(--color-amber)",
        title: "Ask for it, get the answer back",
        pitch: "The ✦ Chat panel answers from your project, and for anything else — “get me the latest purchase order”, “fix the header” — makes a task card, runs it when you say, and posts the result back in the chat. Say “Sonnet, high effort for the code” and the card uses it.",
        why: "A lookup runs as one cheap step and lands with its answer; a change says how it will run (supervised or autonomous) before it starts. Each card in the chat shows where it is, what it needs from you — Allow, Retry, the model to use — and its result when it finishes. Approving and landing stay yours. The chat itself can run on Claude or on a Claude-compatible provider such as GLM, Kimi or Qwen.",
        where: "Top bar → ✦ Chat, or press c",
        headline: true,
      },
      {
        id: "intake",
        icon: "✎",
        color: "var(--color-lime)",
        title: "Improve turns a rough ask into a spec",
        pitch: "Press Improve and Claude writes the Problem, testable Done-when checks and how to verify, then sizes the pipeline.",
        why: "“Claude sized this task: code haiku/low” saves you the three-stage Opus bill on a one-line fix. Nothing changes until you press Use it.",
        where: "New task → Improve",
        go: "board",
      },
      {
        id: "rewrite",
        icon: "✦",
        color: "var(--color-iris)",
        title: "✦ Rewrite a spec after reading the code",
        pitch: "One click on a task's Spec: Opus reads the files the request is about and rewrites it into a clear spec with checks you can test.",
        why: "A spec that names the right files saves a whole run going the wrong way. Your own words are always kept: go back to them, or try another model.",
        where: "Any task → Spec → ✦ Rewrite",
        go: "board",
      },
      {
        id: "terminal",
        icon: ">_",
        color: "var(--color-slate)",
        title: "Your terminal, built in",
        pitch: "A real terminal under the board, opened in the project's folder, or in a task's own copy with Terminal here.",
        why: "Run the app, check git, try a command, without leaving the board or hunting for the right folder. Tabs keep several going, and they keep running when you hide the panel.",
        where: "Top bar → Terminal, or Ctrl + `",
      },
      {
        id: "mcp",
        icon: "⌘",
        color: "var(--color-slate)",
        title: "Sessions that talk to each other",
        pitch: "Every run gets board tools: read its siblings, post messages, split work into subtasks, remember decisions, search what earlier tasks did.",
        why: "A subtask knows what its siblings decided. Project memory hands each later task the decisions that match it, and a run can flag one that is out of date for you to check.",
        where: "Settings → Memory",
        go: "settings",
      },
      {
        id: "delegation",
        icon: "⇄",
        color: "var(--color-iris)",
        title: "Other models, and a plan debate",
        pitch: "Run a stage on a GLM, Kimi Code or Qwen subscription, Ollama, Gemini — or Codex on your ChatGPT plan (no API key, no per-token bill) or an OpenAI key. Have a second model argue with a plan before any code is written.",
        why: "Claude plans; a $20 subscription does the typing. A Codex already on your computer is found by itself: one click on Setup signs it in or puts it on the board — stages, the plan-debate critic at high effort, and pictures. Its newest models show up on their own, each with its effort levels.",
        where: "Setup → Codex · Settings → Providers",
        go: "setup",
      },
      {
        id: "model-lists",
        icon: "☰",
        color: "var(--color-slate)",
        title: "Only the models you want, in each list",
        pitch: "One page decides which models the chat, task stages, the debate and helpers, and pictures offer — with a search box, and a tick per place.",
        why: "Every provider adds a dozen models; hide the ones you never use and the pickers stay short. New models still appear by themselves, and a model you already picked never disappears from under a setting. Every model list can be searched by typing part of a name.",
        where: "Settings → Model lists",
        go: "settings",
      },
      {
        id: "claude-code",
        icon: "✦",
        color: "var(--color-amber)",
        title: "Your Claude Code, all of it",
        pitch: "Runs load your skills, plugins, hooks, tool servers and CLAUDE.md. New projects get /init or a bootstrap.",
        why: "Nothing to set up twice. The board adds a board on top of the Claude you already tuned.",
        where: "Skills tab · Settings → CLAUDE.md",
        go: "skills",
      },
      {
        id: "recommended-skills",
        icon: "★",
        color: "var(--color-moss)",
        title: "Recommended skills, one click to install",
        pitch: "The Skills tab offers design skills worth having — Anthropic's Frontend Design, Emil Kowalski's design engineering, Taste and UI/UX Pro Max — and Microsoft's MarkItDown, which lets Claude read PDFs, Word and Excel files. Install, or Install with Claude.",
        why: "No hunting for the right repository or install command. Install does it for you in one click; Install with Claude does it in a session that asks before every command. Either way they are installed for you rather than one project, so every project's tasks can use them.",
        where: "Skills tab → Recommended",
        go: "skills",
      },
    ],
  },
  {
    title: "It works while you sleep",
    blurb: "Line work up for the night, or for every Monday, and let it run.",
    features: [
      {
        id: "schedule",
        icon: "⏰",
        color: "var(--color-cyan)",
        title: "Start later, or on repeat",
        pitch: "Set a card to start at a time, when your usage limit resets, or every chosen day at a set time.",
        why: "Queue the big job for 2 AM and wake up to it in Review. A repeating schedule makes a fresh card each time, so nightly checks never overwrite each other.",
        where: "Board → ⏰ Schedules · a card's ⏰ Schedule",
        go: "board",
        headline: true,
      },
      {
        id: "runs-out",
        icon: "⇆",
        color: "var(--color-iris)",
        title: "When a provider runs out, work goes on",
        pitch: "If GLM, Kimi or Claude itself runs out mid-task, the task waits for it to reset, or carries on with the fallback you picked. Credit that ran out asks you.",
        why: "The next model is told what the last one did and finds its changes in place, so nothing is redone. Work queued for a provider that is out waits instead of failing.",
        where: "Settings → Providers → When it runs out · a paused card",
        go: "settings",
      },
      {
        id: "awake",
        icon: "☾",
        color: "var(--color-iris)",
        title: "The computer stays awake for it",
        pitch: "While anything is queued, running or scheduled, the computer is asked not to sleep. The screen can still turn off.",
        why: "Night work only happens if the machine is on. If it was off anyway, a missed schedule runs once as soon as the board opens.",
        where: "Settings → Runs & limits",
        go: "settings",
      },
    ],
  },
  {
    title: "You stay in charge",
    blurb: "Unattended does not mean unsupervised.",
    features: [
      {
        id: "modes",
        icon: "✋",
        color: "var(--color-rose)",
        title: "Supervised or autonomous, per task",
        pitch: "Supervised turns every write into an Allow / Deny card. Autonomous works in its own git worktree. Supervised can have its own branch too, landing only when you approve.",
        why: "Pick the leash per task. A repository whose rules say “every write approved” is obeyed, and the board never edits those rules.",
        where: "Approvals tab — press a",
        go: "approvals",
        headline: true,
      },
      {
        id: "steer",
        icon: "✎",
        color: "var(--color-amber)",
        title: "Talk to it while it works",
        pitch: "Open a running task's Chat tab and type — “use the blue from the header”, “skip the tests for now”. It reads it at its next step and carries on.",
        why: "You never have to stop a task and pay for a restart to change one thing. What you typed shows in the transcript, so you can see it was heard.",
        where: "Any running task · Chat tab",
        headline: true,
      },
      {
        id: "line-comments",
        icon: "❝",
        color: "var(--color-cyan)",
        title: "Comment on the code, line by line",
        pitch: "On a task's Changes tab, click any line of the diff and say what is wrong with it. Send hands all your comments to the task in one message, each with its file and line.",
        why: "Review the way you would a pull request, without copying file names and line numbers into a chat box. The task fixes each one and says what it changed.",
        where: "Any task · Changes tab",
        go: "board",
      },
      {
        id: "ask",
        icon: "?",
        color: "var(--color-iris)",
        title: "Claude asks when it matters",
        pitch: "When a choice really needs you, a supervised task stops and asks: options to pick from, or your own words. The card says asks you.",
        why: "No more guessing at the one decision that mattered. It waits for your answer, or, if you'd rather, decides itself after a time you set and says what it chose. An autonomous task never stops: it puts the question on the card with its default and carries on.",
        where: "The task's approvals tab · Approvals tab",
        go: "approvals",
      },
      {
        id: "plan-approval",
        icon: "✓",
        color: "var(--color-iris)",
        title: "Approve the plan before any code",
        pitch: "Turn on plan approval and every task waits after its Plan stage: read it, approve it, edit it, or send it back with a note.",
        why: "A wrong plan is cheapest to fix before a line is written. Mark a task “touches a live system” (a prod chip) and it always waits, every stage is told to dry-run and read back each live change, and the review runs on your strongest model.",
        where: "Settings → Runs & limits · a task's Pipeline tab · its Plan tab",
        go: "settings",
      },
      {
        id: "landing",
        icon: "⤓",
        color: "var(--color-moss)",
        title: "Work lands safely",
        pitch: "Approving pulls main into the task first, re-runs your checks on the result, then merges one task at a time.",
        why: "Conflicts happen in the task's worktree, where Claude can fix them, never in your checkout. A failed merge is aborted, never reset --hard.",
        where: "Settings → Git & merging",
        go: "settings",
      },
      {
        id: "browser",
        icon: "◉",
        color: "var(--color-cyan)",
        title: "It looks at what it built",
        pitch: "When a change is visible, the code stage has it opened in a headless browser, screenshotted and checked, and fixes what looks wrong.",
        why: "The review must say whether it looked, and the screenshots land in the task's Files tab. For extra thoroughness a Sonnet helper can do the clicking and looking. A backend change skips all of it and pays nothing.",
        where: "Settings → Browser, images & plugins",
        go: "settings",
      },
      {
        id: "images",
        icon: "❖",
        color: "var(--color-moss)",
        title: "It makes the pictures it needs",
        pitch: "Once Codex is linked, a task that needs an illustration, an icon or a placeholder photo makes one on your ChatGPT plan and saves it into the project. Cloudflare or Pollinations work too, with your own key.",
        why: "No grey boxes and no stopping to ask you for a picture: the task is told who makes its pictures and uses them. With no picture maker ready (Codex on Windows cannot make them yet), tasks simply run without the tool, as they would anyway. Your own Claude Code can have the same tool.",
        where: "Settings → Browser, images & plugins",
        go: "settings",
      },
      {
        id: "watch",
        icon: "◉",
        color: "var(--color-rose)",
        title: "Watch it click through your app",
        pitch: "When a task opens its app in the browser, a live chip appears on its card: open it and watch the page as it clicks and types.",
        why: "You see what it is testing while it tests, not only the screenshots afterwards. No windows pop up over your work, and the picture only streams while you watch.",
        where: "A card's live chip · the task's Browser tab",
        go: "board",
      },
      {
        id: "guardrails",
        icon: "⛨",
        color: "var(--color-rust)",
        title: "Guardrails that can't be clicked past",
        pitch: "Blocked commands, never kill by name, a cost ceiling per task and per stage, and loop detection.",
        why: "Refused before any card appears. A card for rm -rf / is only a chance to click the wrong button.",
        where: "Settings → Runs & limits",
        go: "settings",
      },
    ],
  },
  {
    title: "It respects your time and money",
    blurb: "Honest numbers, and no babysitting.",
    features: [
      {
        id: "usage",
        icon: "◔",
        color: "var(--color-iris)",
        title: "Usage limits pause, then resume by themselves",
        pitch: "Your 5-hour and weekly windows sit in the top bar, with your other providers' plans below them. A task that hits a limit pauses and continues when it resets.",
        why: "Nothing fails at 2 a.m. because a window ran out, and nothing already finished is redone. GLM, Kimi Code and OpenRouter report what is left; reading it is free.",
        where: "Top bar · usage meters",
        headline: true,
      },
      {
        id: "cost",
        icon: "$",
        color: "var(--color-lime)",
        title: "What every task really cost",
        pitch: "Tokens, dollars and time per stage. A task that reaches its cost ceiling pauses and asks — Continue with a bit more, or Stop — instead of throwing the work away.",
        why: "You learn which stages are worth their model, and money never fails a task at 90% done. The dashboard shows where the money goes — stages, helpers, critic, chat, intake — plus first-pass rate and where runs fail.",
        where: "Dashboard · the cost on any task",
        go: "dashboard",
      },
      {
        id: "alerts",
        icon: "♪",
        color: "var(--color-rose)",
        title: "It calls you when it needs you",
        pitch: "A colour and a sound for each event: needs you, ready for review, landed, failed, all clear. Allow or Deny right on the pop-up.",
        why: "Walk away. The bell's inbox lists everything waiting on you and what happened while you were gone; a pop-up closes itself once its card is dealt with, wherever you did it.",
        where: "Top bar · the bell and its ▾",
        headline: true,
      },
      {
        id: "recall",
        icon: "⌕",
        color: "var(--color-slate)",
        title: "Nothing is lost",
        pitch: "Search specs, transcripts, results and memory with /. Chat continues a task's session; Follow-up starts a linked one. ⤓ Record saves a task's whole story as one file.",
        why: "Days later you can still find what a run decided and why, and pick it up without starting over. The record keeps every step, question, approval and cost after the transcript is pruned.",
        where: "Press / anywhere",
        go: "sessions",
      },
      {
        id: "looks",
        icon: "◈",
        color: "var(--color-cyan)",
        title: "Three looks, five fonts, one board",
        pitch: "Dark graphite, warm light, or Navy — a deep blue ground with JetBrains Mono for code. Auto follows the computer between light and dark. Aa picks the font: SF Pro (the default), Inter, Segoe UI, Roboto or IBM Plex Sans.",
        why: "A board you look at all day should look the way you like. Every colour on it is a swap of the same tokens, so cards, charts and the terminal all change together, and the font you pick holds in every theme.",
        where: "Top bar · ◐ ☀ ☾ ◈ and Aa · Settings → Appearance",
        go: "settings",
      },
    ],
  },
];

export const ALL_FEATURES = GROUPS.flatMap((g) => g.features);
export const HEADLINES = ALL_FEATURES.filter((f) => f.headline);

export const SHORTCUTS: [string, string][] = [
  ["1 – 9", "switch tabs"],
  ["a", "approvals"],
  ["c", "open or close the chat"],
  ["Ctrl + `", "show or hide the terminal"],
  ["y / n", "allow / deny the top approval, on the Approvals tab"],
  ["/  or  Ctrl K", "search everything"],
  ["Ctrl + / − / 0", "zoom the board"],
  ["Esc", "close whatever is open"],
];
